version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: calidad2024
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew' -o -name '.gradle*' | \
            sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}

      - run:
          name: Install MySQL Client
          command: sudo apt-get update && sudo apt-get install -y default-mysql-client
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in seq 1 10 ;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Create Database
          command: |
            mysql -h 127.0.0.1 -u root -p123456 -e "CREATE DATABASE IF NOT EXISTS calidad2024;"
            mysql -h 127.0.0.1 -u root -p123456 calidad2024 < src/resources/db.sql
      - run:
          name: Verify Chrome Installation
          command: google-chrome --version

      - run:
          name: Run Unit Tests
          command: mvn -Dtest=com.mayab.quality.unittest.service.UserServiceTest test

      - run:
          name: Run Integration Tests
          command: mvn -Dtest=com.mayab.quality.integration.UserServiceTest test

      - run:
          name: Run Functional Tests
          command: mvn -Dtest=com.mayab.quality.functional.CRUDSeleniumTest test

      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths: ~/.m2/repository
  
  deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deployment Steps
          command: echo "El Deployment se ejecutó con exito"

workflows:
  build-and-deployment:
    jobs:
      - build
      - deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - main
